name: financy_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  mockito: ^5.5.1

flutter:
  uses-material-design: true
